### ISSUE TITLE
Calendar Page

### ISSUE THREAD

**Issue by 04sravya** [cse110-sp24-group23/dev-journal#12]
**Feature Description**
As a user, I want to be able to access the daily logs of different days in the month. 

We want to have:

- A calendar widget with links that lead to each day's log
- Ability to view different months
- Populate days by months

**Sub-Issues**

- [ ] Calendar page boilerplate HTML
- [ ] Populate days based on month
- [ ] Identification of today's date

**Comment by danwyl** [comment]
Moving to next sprint
