### ISSUE TITLE
Notes Page

### ISSUE THREAD

**Issue by 04sravya** [cse110-sp24-group23/dev-journal#16]
**Feature Description**
As a user, I want to be able to save different notes where I can jot down information that may not pertain to a specific date.

We want to have:

- Clickable icons that represent different saved notes. When clicked, the note is revealed and can be edited
- Method to add and delete notes
- Markdown functionality within the notes

**Sub-Issues**

- [ ]  Gallery View Boilerplate
- [ ] Implement opening a note
- [ ] Research and Implement Markdown Editor #10

**Comment by danwyl** [comment]
Moving to next sprint
